<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact-List</title>
    <link rel="stylesheet" href="stylesheet.css">
</head>
<body>

<!-- Move the header to a separate file that can be reused -->
<header>
    <h1>Contact List</h1>
</header>

<nav>
    <!-- Show a list of all contacts here -->
</nav>

<main>
    <!-- Show the details of the selected contact here -->
</main>

</body>
</html>
